### ISSUE TITLE
OpenKH Fails to Build and Boot Game Due to Missing bgm/music122.bgm and bgm/music123.bgm

### ISSUE THREAD

**Issue by Necrofitz** [KH2FM-Mods-Num/Music-Rando#1]
Updated the mod as prompted by OpenKH, and I see the commit note is that the two noted tracks, 122 and 123, were removed. There seems to be a kink somewhere in the chain though, as upon attempting to build and run with a fresh running of the music randomizer exe, I only get the following:

[004.048]ERR Patcher failed: One or more errors occurred. (The mod does not contain the file bgm/music123.bgm) (The mod does not contain the file bgm/music 122.bgm)

Attempts to simply redownload the mod still result in the same error. Adding the two tracks back in from a backup allows the mod to work as normal.

**Comment by Rikysonic** [comment]
I'm opening a PR to fix that, the issue is that the python script still searches for these 2 tracks and adds them in mod.yml.

**Comment by Rikysonic** [comment]
My fork is updated and it's working, install this one while Num merges my fix: `Rikysonic/Music-Rando`

**Comment by 1234567890num** [comment]
#2
